[project]
name = "viper"
version = "0.0.0"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT OR Apache-2.0"
dependencies = [
    "numpy>=2.3.5",
    "scikit-learn>=1.8.0",
    "tqdm>=4.67.1",
]
